### ISSUE TITLE
Consider removing build target kind

### ISSUE THREAD

**Issue by jvican** [scalacenter/bsp#12]
BSP has the notion of `BuildTargetKind`. A build target kind describes the capabilities of a build target. From the spec:

```scala
object BuildTargetKind {
  val Library = 1
  /** This target can be compiled and tested via
    * method buildTarget/test */
  val Test = 2
  /** This target can be tested via method
    * buildTarget/test and may run slower compared to a Test. */
  val IntegrationTest = 3
  /** This target can be run via method buildTarget/run */
  val Main = 4
}
```
  
I think we should remove build target kind because build tools rarely know a priori what kind of target the user describes. To know whether a target is a library, can be tested, or has a main, the build tool has to compile that target and inspect the bytecode.

**Comment by jvican** [comment]
What do you think @olafurpg?

**Comment by olafurpg** [comment]
I think we should keep them since it's important for clients to know if it's possible or even logical to test/run a given target. It doesn't make sense to run a library targets that has no main. Likewise, an app target (with a `main`) should not be able to test. Build tools like bazel are able to provide this information. Build tools like sbt can be conservative and permit run+test for all targets and crash instead at runtime.

Question if a target should instead have a list of "capabilities"? This would allow a build server to say if a target can be run/test.

**Comment by jvican** [comment]
(After offline discussion, we agreed that it would still be nice if build tools like Bazel could specify this information, whereas more flexible build tools like maven, sbt or gradle can be conservative and instead allow all operations on build targets.)
   
I think that we should remove the list of kinds and also `IntegrationTest`. Bazel doesn't allow to define an integration test target and the `IntegrationTest` kind doesn't describe a new capability, it's just a `Test` target kind whose execution is slower.
  
Here's what I propose:
  
```scala
object BuildTargetKind {
  val Library = 1 // compile
  val Test = 2 // compile + test
  val Main = 3 // compile + run
  val Generic = 4 // compile + test + run
}
```
  
Where `Generic` means that any both `test` and `run` can be run in that target. This would be the default for the flexible build tools mentioned above.
  
The only other combination we're not handling is a target that can be both tested and run at the same time. I'm for ignoring it, for two reasons:
  
* Bazel doesn't support it either (a target can either be run or tested and they exclude each other).
* It is rare to find such a target in the wild, and even more so that the build tool allows you to express it.

If you're fine with this I'll add this change to my open PR @olafurpg

**Comment by olafurpg** [comment]
@jvican How about separating the label of the target from the operations it supports?

```scala
trait BuildTarget {
...
  def compileProvider: Boolean // true == can be compiled
  def testProvider: Boolean    // true == can be tested
  def runProvider: Boolean     // true == can be run
  def labels: List[String]     // free-form list of labels
}
```

- avoids introducing kinds like `Generic`
- makes it easy to introduce other kinds down the road, like "bench" 
- allows users to create any labels, such as "test" or "integration test", "app", "cli", "server", ...
