### ISSUE TITLE
Reconsider workspace/ and textDocument/ methods

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bsp#2]
Currently we have two methods that enter the LSP namespace

* workspace/buildTarget
* textDocument/buildTarget

we should consider moving them into separate namespaces to avoid conflicts with LSP.

**Comment by laughedelic** [comment]
After reading the draft I wanted to ask why do you introduce a separate namespace `build/` instead of reusing existing LSP commands as much as possible.

**Comment by olafurpg** [comment]
Good question. It should be possible to implement BSP and LSP in the same JSON-RPC server. For example, if we reused `initialize` then sbt server would have to choose between BSP or LSP. Most of the BSP methods are under `buildTarget/` where `BuildTarget` plays a similar role in BSP as `TextDocument` plays in LSP.

BSP does reuse several LSP methods, like `window/logMessage` and `textDocument/publishDiagnostics`.

**Comment by jvican** [comment]
Any ideas about which other namespaces we should use aside from `window`, `textDocument` and `workspace`? Should we just prepend `build/` to all of them? (I think this is the most elegant solution since the current namespaces make sense.)

**Comment by olafurpg** [comment]
I think it's a good idea to prefix BSP methods with `build/` so we'll have

* `build/publishDiagnostics`
* `build/logMessage`
* ...

This avoids any conflicts with LSP methods. WDYT?

**Comment by jvican** [comment]
Done in #5
