### ISSUE TITLE
Should we model compilation errors as JSON-RPC errors?

### ISSUE THREAD

**Issue by jastice** [scalacenter/bsp#20]
@jvican how compile errors in a `CompileResult` should be communicated. 

In the current implementation, a `CompileResult` contains no specific information as to compile errors, but by being a successful result it signals that the overall compilation succeded. In the case of any error, a JsonRpc error result is returned. Individual per-target `CompileReport` notifications communicate the results during compilation.

The argument for this mechanic is that a client can assume a successful result allows to resume normally with dependent tasks.

The argument against is that compile errors are a part of normal operation of the compiler, and only internal errors should trigger exception handling.

To be discussed for bsp 2.0

**Comment by jvican** [comment]
Note that the same applies here to `TestReport` and that this is the way LSP does it by default.

**Comment by olafurpg** [comment]
I recommend using JSON-RPC errors only for 1) error handling at the JSON-RPC layer and 2) internal server error. Application-level errors like "compilation failed" should be encoded in the protocol messages.

**Comment by jvican** [comment]
> "error: code and message set in case an exception happens during the request."
  
Yeah, which are JSON-RPC errors.
  
I also think that we should perhaps move valid errors like compilation failed to the BSP layer instead of JSON-RPC in BSP 2.0. That will be conceptually simpler.

**Comment by jastice** [comment]
Agree, and it more cleanly separates "business" logic and implementation logic.

**Comment by olafurpg** [comment]
It seems we are in agreement to use protocol-level messages for error reporting and leave unexpected server errors to the JSON-RPC layer. I think we can close this ticket.
