### ISSUE TITLE
Allow clients to discover and connect to running bsp servers

### ISSUE THREAD

**Issue by jvican** [scalacenter/bsp#32]
BSP clients like IntelliJ need to find a way to discover and run bsp servers, so that when they are started they can immediately connect to a build server and extract all its build information.

In a short discussion with @alexarchambault regarding Jupyter kernels, I learned that Jupyter solves a similar problem with [kernelspec](https://jupyter-client.readthedocs.io/en/stable/api/kernelspec.html) and [kernelspecs](https://jupyter-client.readthedocs.io/en/stable/kernels.html#kernelspecs). Kernelspec is the specification of the configuration file that contains the required information to detect which build servers are running in a machine and how to connect to them. The specification defines a JSON format similar to what we would like to use for BSP servers:
  
```json
{
 "argv": ["python3", "-m", "IPython.kernel",
          "-f", "{connection_file}"],
 "display_name": "Python 3",
 "language": "python"
}
```
  
The above snippet shows only a subset of the kernelspec file with is most important fields and is usually stored in `.local/share/jupyter/kernels` in a Linux machine (see the linked docs for all the valid locations).
  
I propose to adopt a similar/identical solution to what kernelspec does to solve this problem. We could only apply minimal changes to the specification so that we have a command to run the BSP server in the current operating system (`argv`), the display name and the language. The client could use this information to offer the end user the possibility of choosing a BSP server if there is more than one server running that accepts a given language.
  
We may want to add the resulting spec into the BSP specification.
  
Let me know what your thoughts are. This ticket is mainly to explore how technically feasible adopting a variant of kernelspec is for bsp.

**Comment by jastice** [comment]
From discussion, we agreed on this simplest reasonable variant:

* no global bsp tool declaration
* a workspace may contain a `.bsp` directory with json files specifying how to connect to a local bsp server that supports the projects

Typical workflow:
1. user clones a project and installs the build tool needed to build it
2. user runs build tool command to generate a `<workspave>/.bsp/tool.json` file
3. user instructs client to import the workspace
4. client detects `tool.json` and runs build tool accordingly. In the case of multiple supported build tools, the client can give the user a choice which to use.

Alternative workflow:
1. user defines a custom script for the project that runs the build tool
2. user defines `.bsp/tool.json` themselves and checks it in with the project
3. as above

This leaves open the option for clients to implement dedicated build tool support that makes the common cases easier. For instance, a client may detect that the project contains a `build.sbt` file and run sbt itself to create the `.bsp/sbt.json` definition.
