### ISSUE TITLE
Run task without cache vs cleaning

### ISSUE THREAD

**Issue by jastice** [scalacenter/bsp#34]
We want to support a way for clients to run tasks, especially compiles, without cache, i.e. a non-incremental build.

One way to do this is to support a `clean` request that asks to remove any products of a build target.

Another way would be to add a flag to the compile request, and potentially other tasks, that requests a full rebuild.

What considerations affect the choice of these options, and are there other options?

**Comment by olafurpg** [comment]
I would love to avoid adding side-effectful `clean` command to the protocol since some build tools don't provide this functionality. I propose instead that we indicate in the `buildTarget/compile` request whether the compilation should be a "full compile" or "incremental compile" leaving it to the server to interpret how that should run. We can either use the existing `CompileParams.arguments` or add a new `CompileParams.mode = INCREMENTAL | CLEAN | ???`

**Comment by jastice** [comment]
In the case of compilation, I think the use-case is common enough to warrant a protocol-defined argument rather than freeform.

I'm not sure about other cases. When we go beyond compilation to any type of task with persistent output (eg jar assembly, test reports, download cache) do we want a standard way to just clean them, vs request a non-cached execution?

The `clean` is easier to define in a standard way: One request to just remove whatever cached outputs this build target may produce. Non-cached execution would have to be a parameter for any possible task supporting this..

**Comment by jastice** [comment]
I think for the time being it's reasonable to add a `CompileParams.mode` in any case

**Comment by olafurpg** [comment]
When I think of it more I agree that adding a `clean` request makes sense. A lot of build tools do support clean and I see value in having a tool-agnostic endpoint for this functionality. The build tool can declare that it doesn't support clean during the initialize handshake.

**Comment by olafurpg** [comment]
To fix this ticket I propose to add a new request endpoint `buildTarget/clean`

```
// buildTarget/clean: request from client to server
trait CleanParams {
  def targets: List[BuildTargetIdentifier]
}
trait CleanResult {
  
}
```

Any suggestion what to put in `CleanResult`? We could add `def cleaned: Boolean`, where `cleaned=true` means the clean succeeded and `cleaned=false` means nothing was cleaned. This would be consistent with LSP `workspace/applyEdit` https://microsoft.github.io/language-server-protocol/specification#workspace_applyEdit
