### ISSUE TITLE
Initialization request, additional information

### ISSUE THREAD

**Issue by jastice** [scalacenter/bsp#42]
As discussed, we want additional data in the `InitializeBuildResult`:

* server info: String containing basic information about the server (typically name and version). This is primarily useful for debugging purposes
* bsp spec version: The version of the bsp specification this server implements (semver string)

Questions that I just came up with:
* should we have an arbitrary json data field that the server can fill as they please?
* should servers be able to communicate multiple bsp spec versions? This would require some further version negotiation in the protocol. Probably this is best left to server startup.

**Comment by jvican** [comment]
> should we have an arbitrary json data field that the server can fill as they please?
  
In my opinion, this is always good.
  
> should servers be able to communicate multiple bsp spec versions? This would require some further version negotiation in the protocol. Probably this is best left to server startup.
  
Yes, I would leave it for server startup, and I would also leave the server info (name and version) there, adding only the BSP version to `build/initialize`. I'll expand on this point in the proposal to connect to the BSP server that I'm working on and will be submitted today.

**Comment by olafurpg** [comment]
I agree with @jvican.

How about the following data structures?
```scala
trait InitializeBuildParams {
  def info: InitializeInfo
}
trait InitializeBuildResult {
  def info: InitializeInfo
}
trait InitializeInfo {
  /** BSP version that the client/server speaks. */
  def bspVersion: String
  /** Name of the client/server, can include the version number of the client application.
    * Can be displayed to the user to notify an an established connection. */
  def name: String
  /** Additional metadata about the client/server. */
  def data: Option[Json]
}
```

**Comment by jastice** [comment]
@olafurpg why the nested `info`? Seems like it could go all directly into the params

**Comment by olafurpg** [comment]
It was to share the same fields between the params and result types, otherwise we have to copy the `bspVersion,name,data` fields + docstrings in both objects. I don't feel strongly about it however.

**Comment by jastice** [comment]
Makes sense, but I think request params and result data should be evolvable individually

**Comment by jvican** [comment]
I agree; it's not clear to me it's safe to infer they will always be the same. I would just inline the fields.

**Comment by olafurpg** [comment]
Sounds good to me, let's inline the fields 👍

**Comment by olafurpg** [comment]
@jvican can we include this change in #53? It's related to the `BspConnectionDetails.`

**Comment by jvican** [comment]
@olafurpg Yes! I'll add this information there.
