### ISSUE TITLE
Rename textDocument/buildTargets to buildTarget/inverseSources

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bsp#48]
Currently, we have 
```
# Short names
buildTarget/compile - CompileParams
build/showMessage - ShowMessageParams
...

# Odd fish
textDocument/buildTargets - TextDocumentBuildTargetsParams
```

It's odd because it's the only endpoint in the `textDocument/` "namespace" (which is used by LSP) and also because the parameter type name includes both namespace + method.

I propose we rename `textDocument/buildTargets` into `buildTarget/inverseSources` to stress the relationship with `buildTarget/sources` and then use `InverseSourcesParams` for the parameter type.

**Comment by jvican** [comment]
Sounds good to me. Making this duality explicit in the name is always good and will clarify reading the specification.
