### ISSUE TITLE
MUST vs SHOULD requirements in the spec

### ISSUE THREAD

**Issue by jastice** [scalacenter/bsp#59]
continuing [discussion](https://github.com/scalacenter/bsp/pull/49#discussion_r228887507) in #49 on whether the spec should require certain notifications ("must") or only strongly suggest them ("should")

Case-in-point here: What was previously `CompileReport` and `TestReport` notifications, in #49 subsumed by generic task notifications with predefined `dataKind`.

**Comment by jastice** [comment]
In general, I think the protocol should make it as simple as possible to write a compliant minimal server or client.

For the server this means: 
* the less functionality it has to provide, the easier it is to write.

For the client this means: 
* the more assumptions it can make about behavior of the server, the easier
* the more functionality it can ignore, the easier

Where these goals are not in conflict, I think it is prudent to not require specific behavior in the spec, but rather suggest the standard way for an implementation to provide a better integration.

In the case of task notifications, simple clients may choose to drop them altogether or merely log their messages. Simple servers may only report success or failure. A client can not expect any particular notification to be part of a task.

For example, a compile request may not trigger any compilation task at all, because the complete build has already been cached. So it should not be strictly required to send these notifications in the first place.

**Comment by olafurpg** [comment]
I agree @jastice

**Comment by jvican** [comment]
I'm fine with that approach. In general, though, I prefer explicitness over implicitness. The more explicit and constrained the protocol is for me as an implementor of the BSP server, the better. But this is a personal opinion, so let's move forward here.

**Comment by jastice** [comment]
Adapted #49 accordingly.
