### ISSUE TITLE
FAQ?

### ISSUE THREAD

**Issue by dsilvasc** [scalacenter/bsp#6]
Hi,

Would it be possible to provide an FAQ in the readme with answers to questions like:

- What's the relationship between BSP and Language Server Protocol?
- What's the relationship between implementations of BSP and implementations of LSP like https://github.com/scalameta/metals or https://github.com/dragos/dragos-vscode-scala ?
- Should non-Scala participants in the protocol generate data types from bsp.proto or is it preferrable to use pre-generated artifacts in maven (or other repos)?

**Comment by heathermiller** [comment]
Yes! 💯 on this! Great idea :)

**Comment by dsilvasc** [comment]
thanks for that, makes sense now :)
