### ISSUE TITLE
Re-enable BloopSuite

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bsp#61]
While working on #57 `BloopSuite` started failing with 

```
[E] Boxed Error
```

which is expected since the PR has breaking changes in bsp4s. We should re-enable `BloopSuite` once bloop has upgraded to the latest bsp4s.

**Comment by jastice** [comment]
Do you think we still need this, given mock server and generator serialization tests? The bloop-bsp suite might better go to the bloop repo

**Comment by olafurpg** [comment]
I'm fine removing `BloopSuite`
