### ISSUE TITLE
Add client capabilities for task progress notifications

### ISSUE THREAD

**Issue by olafurpg** [scalacenter/bsp#77]
Currently, there is no way for clients to skip receiving `build/task{Start,Progress,Finish}` notifications. The client should only receive these notifications if it uses them.

I propose we update `BuildClientCapabilities` to include whether these notifications should be sent or not
```diff
trait BuildClientCapabilities {
  /** The languages that this client supports.
    * The ID strings for each language is defined in the LSP.
    * The server must never respond with build targets for other
    * languages than those that appear in this list. */
  def languageIds: List[String]

+  def taskProgress: "all" | List[String] | null
+  def taskStart: "all" | List[String] | null
+  def taskFinish: "all" | List[String] | null
}
```

Where the values can be one of the following types

- `all`: send all notifications
- `List[String]`: send only notifications `dataKind` in this list
- `null`: don't send notifications

Any suggestions for a better type encoding? I made it a union type here for simplicity but we should try to avoid that in the final version if possible.

**Comment by jastice** [comment]
Good idea. 

I'm not sure the `dataKind` is appropriate as a filter. progress notifications may have empty dataKind. I think it's sufficient to make these fields boolean, and let the client deal with filtering or showing anything in more detail.

On the other hand, a client already can and needs to ignore any messages it doesn't want to display. Are you worried about creating communication overhead when it doesn't add any value?

**Comment by olafurpg** [comment]
I agree it would make sense make those booleans. The main motivation was indeed to reduce overhead since I was receiving many thousand task progress notifications from Bloop when compiling medium sized projects (one notification per phase/file). However, think we will end up reducing the amount of `taskProgress` notifications from Bloop so it won't be a problem.

**Comment by jastice** [comment]
Okay, I currently feel like the granularity of progress notifications should be decided by the build tool's design or configuration, so that we can keep the protocol simpler. What do you think?

**Comment by olafurpg** [comment]
I agree.
