### ISSUE TITLE
Build server life cycle is managed by platform 

### ISSUE THREAD

**Issue by PavelSosin** [scalacenter/bsp#81]
In the cloud EDI architecture BIuild server is a part of workspace tool chain. Client doesn't need to manage its lifecycle. Platform is responsible for toolchain lifecycle. When workspace is started all required tools are started.

**Comment by jastice** [comment]
What is the issue? I'm not sure what cloud EDI architecture you are referring to.

BSP doesn't require the client to manage the build server lifecycle. The [connection protocol](https://github.com/scalacenter/bsp/blob/master/docs/bsp.md#bsp-connection-protocol) only requires an adapter that is able to communicate with the build tool.

**Comment by jvican** [comment]
Closing, non-actionable questions can be done over in our gitter channel: https://gitter.im/scalacenter/bsp
